# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PruebaGradientDescent
#'
#' @export
#' @useDynLib GradDesc
GradientDescentSumaCuadrados <- function(A, b) {
    .Call('GradDesc_GradientDescentSumaCuadrados', PACKAGE = 'GradDesc', A, b)
}

