# Compilación de la versión ampliada de la biblioteca Purple en estático para Windows


# Como hacer el makefile: https://www.safaribooksonline.com/library/view/c-cookbook/0596007612/ch01s17.html
# Specify extensions of files to delete when cleaning
CLEANEXTS   = o lib 

# Specify the target file and the install directory
OUTPUTFILE  = ./lib/Purple.lib

objects = ./Purple/bin/ObjectiveFunction.o ./Purple/bin/OptimizationAlgorithm.o ./Purple/bin/GradientDescent.o ./Purple/bin/SumaCuadrados.o
CXXFLAGS = -m64 -Wall
GCCPATH=C:/Rtools/gcc-4.6.3/
CXX=$(GCCPATH)bin/g++
# Default target
.PHONY: all
all: $(OUTPUTFILE)

$(OUTPUTFILE): $(objects)
	$(GCCPATH)i686-w64-mingw32/bin/ar rcs $@ $^

 
./Purple/bin/ObjectiveFunction.o: ./Purple/ObjectiveFunction/ObjectiveFunction.cpp
	$(CXX) $(CXXFLAGS) -c ./Purple/ObjectiveFunction/ObjectiveFunction.cpp -o  ./Purple/bin/ObjectiveFunction.o

./Purple/bin/OptimizationAlgorithm.o: ./Purple/OptimizationAlgorithm/OptimizationAlgorithm.cpp
	$(CXX) $(CXXFLAGS) -c ./Purple/OptimizationAlgorithm/OptimizationAlgorithm.cpp -o  ./Purple/bin/OptimizationAlgorithm.o

./Purple/bin/GradientDescent.o: ./Purple/OptimizationAlgorithm/GradientDescent.cpp
	$(CXX) $(CXXFLAGS) -c ./Purple/OptimizationAlgorithm/GradientDescent.cpp -o ./Purple/bin/GradientDescent.o

./Purple/bin/SumaCuadrados.o: ./Purple/ObjectiveFunction/SumaCuadrados.cpp
	$(CXX) $(CXXFLAGS) -c ./Purple/ObjectiveFunction/SumaCuadrados.cpp -o ./Purple/bin/SumaCuadrados.o

# files is required; this is handled by make's database of
# implicit rules

.PHONY: clean 
clean:
	for file in $(CLEANEXTS); do rm -f ./lib/*.$$file; rm -f ./Purple/bin/*.$$file; done


