// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// PruebaGradientDescend
Rcpp::NumericVector PruebaGradientDescend();
RcppExport SEXP GradDesc_PruebaGradientDescend() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(PruebaGradientDescend());
    return __result;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP GradDesc_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
