# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' GradientDescentSumaCuadrados
#'
#' @param A Matriz con regresores
#' @param b Vector objetivo
#'
#'
#' @export
GradientDescentSumaCuadrados <- function(A, b) {
    .Call('GradDescAutocontenido_GradientDescentSumaCuadrados', PACKAGE = 'GradDescAutocontenido', A, b)
}

